version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.angular/cache
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: angular-test
  test:
    build:
      context: ./frontend
      dockerfile: test/Dockerfile.dev
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
      - .env.2test
    ports:
      - "4100:4100"
    container_name: e2e-test
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
      - .env.2test
    container_name: flask-test