version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.angular/cache
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: angular-dev
  test:
    build:
      context: ./frontend
      dockerfile: test/Dockerfile.dev
    depends_on:
      - frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4100:4100"
    container_name: test-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    container_name: flask-dev

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    container_name: pg-dev

volumes:
  pgdata_dev: