version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    container_name: angular-frontend
  test:
    build:
      context: ./frontend
      dockerfile: test/Dockerfile.dev  # 或 Dockerfile.prod，如果裡面有測試流程
    depends_on:
      - frontend
    network_mode: service:frontend
    container_name: test-prod

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - backend/.env
    restart: always  

  db:
    image: postgres:16
    restart: always
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/.env
    ports:
      - "5432:5432"