version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    container_name: angular-frontend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
      - .env.3prod
    restart: always
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: pg-prod
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-prod
  celery:
    build:
      context: ./celery
      dockerfile: Dockerfile.prod
    command: celery -A celery_worker worker --loglevel=info
    env_file:
      - .env
      - .env.3prod
    depends_on:
      - redis
      - backend
    container_name: celery-prod
volumes:
  pgdata_prod: