version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    container_name: angular-frontend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
      - .env.3prod
    restart: always
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: pg-prod
volumes:
  pgdata_prod: